### ISSUE TITLE
stay compatible?

### ISSUE THREAD

**Issue by borzel** [xcp-ng/win-xenguestagent#1]
Citrix uses the following WMI names
* CitrixXenStoreBase
* CitrixXenStoreWatchEvent
* CitrixXenStoreSession

If we compile our own PV-Drivers, we should maybe use other names.
What do you think @olivierlambert ?

**Comment by olivierlambert** [comment]
Ehhmm that's a good question. Any idea @stormi ?

**Comment by borzel** [comment]
First I try to implement a switch at buildtime, which chooses between
* XCP-ng PV-driver mode (default)
* Citrix PV-driver mode

**Comment by borzel** [comment]
Since we build all our own (PV-Drivers and management agent) this is no longer needed
