### ISSUE TITLE
XCP-ng guest tools support for CloudLinux

### ISSUE THREAD

**Issue by iServU** [xcp-ng/win-xenguestagent#4]
I run a client website hosting VM using CloudLinux to allow for client usage restrictions at the kernel level.

Current OS version is:

When I try to install the guest tools using CentOS which is what CloudLinux (i think) is based on, I receive errors saying that the host OS is not recognized.

Here is the process I followed:
[root@cpsvr01 glopez]# mount /dev/cdrom /mnt
mount: /dev/sr0 is write-protected, mounting read-only

Then: 

[root@cpsvr01 glopez]# /mnt/Linux/install.sh
Fatal Error: Failed to determine Linux distribution and version.

**Comment by stormi** [comment]
Hi. This repository is about the guest agent on linux. Can you close this issue and open one on https://github.com/xcp-ng/xcp ?

**Comment by iServU** [comment]
My apologies, just saw guest tools and bam! LOL
Fixing this now!



Sincerely,


Gabriel Lopez
Chief Technologist
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
Galonet Tech Corp
Miami, FL, United States
www.galonet.com<http://www.galonet.com/>
[http://www.galonet.com/galonet.com.logo.email.png]<http://www.galonet.com/galonet.com.logo.email.png>

**Comment by borzel** [comment]
It seems you have not found the close button yet ;-)

So I do it for you...
